name: docs.devradar.io

on: [push]

jobs:
  site:
    name: publish docs
    runs-on: 'ubuntu-20.04'
    steps:
    - uses: actions/checkout@v2
      with:
        lfs: true
    - name: Checkout LFS objects
      run: git lfs checkout
    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.74.2'
    - name: build hugo page
      run: |
        hugo --gc --minify -d _site --baseURL //docs.devradar.io
        touch _site/.nojekyll
        echo "docs.devradar.io" > _site/CNAME
    - name: publish to gh-pages
      uses: JamesIves/github-pages-deploy-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: _site
      if: github.event_name == 'push' && github.ref == 'refs/heads/master'
